apiVersion: v1
kind: ServiceAccount
metadata:
  name: relay-sa
  namespace: k8s-platform-lab
  labels:
    app: relay
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: relay-event-reader
  namespace: k8s-platform-lab
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: relay-event-reader-binding
  namespace: k8s-platform-lab
subjects:
  - kind: ServiceAccount
    name: relay-sa
    namespace: k8s-platform-lab
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: relay-event-reader